# View rules at https://github.com/sasstools/sass-lint/tree/master/docs/rules
rules:
    # Extends
    extends-before-mixins: 1
    extends-before-declarations: 1
    placeholder-in-extend: 1

    # Mixins
    mixins-before-declarations: 1

    # Line Spacing
    one-declaration-per-line: 1
    empty-line-between-blocks: 1
    single-line-per-selector: 0

    # Disallows
    no-color-keywords: 1
    no-color-literals: 1
    no-css-comments: 1
    no-debug: 1
    no-disallowed-properties: 1
    no-duplicate-properties: 1
    no-empty-rulesets: 1
    no-extends: 1
    no-important: 0
    no-invalid-hex: 1
    no-mergeable-selectors: 1
    no-misspelled-properties: 1
    no-qualifying-elements: 1
    no-trailing-whitespace: 1
    no-trailing-zero: 1
    no-transition-all: 1
    no-universal-selectors: 1
    no-vendor-prefixes: 1
    no-warn: 1
    property-units: 1

    # Nesting
    declarations-before-nesting: 1
    force-attribute-nesting: 1
    force-element-nesting: 1
    force-pseudo-nesting: 1

    # Name Formats
    function-name-format: 1
    
    mixin-name-format: 1
    placeholder-name-format: 1
    variable-name-format: 1

    # Style Guide
    attribute-quotes: 1
    bem-depth: 1
    border-zero: 1
    brace-style: 1
    clean-import-paths: 1
    empty-args: 1
    hex-length: 1
    hex-notation: 1
    
    leading-zero: 0
    
    
    property-sort-order: 0
    pseudo-element: 1
    
    
    shorthand-values: 1
    url-quotes: 1
    variable-for-property: 1
    zero-unit: 1

    # Inner Spacing
    space-after-comma: 1
    space-before-colon: 0
    space-after-colon: 1
    space-before-brace: 1
    space-before-bang: 1
    space-after-bang: 1
    space-between-parens: 1
    space-around-operator: 1

    # Final Items
    trailing-semicolon: 1
    final-newline: 1

    # Custom
    class-name-format: 0
    id-name-format: 0
    max-line-length: 0
    max-file-line-count: 0
    nesting-depth: 0
    no-attribute-selectors: 0
    no-combinators: 0 # Plus sign
    no-ids: 0
    no-url-domains: 0
    no-url-protocols: 0
    quotes:
        - 2
        -
            style: double

    # Arguable
    indentation:
        - 1
        -
            size: 4
    no-color-hex: 0
